apiVersion: v1
kind: Service
metadata:
  name: App1-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App1
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30021
---
apiVersion: v1
kind: Service
metadata:
  name: App3-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App3
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30070
---
apiVersion: v1
kind: Service
metadata:
  name: App2-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App2
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30022
---
apiVersion: v1
kind: Service
metadata:
  name: App4-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App4
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30060
---
