kind: Service
apiVersion: v1
metadata:
  name: adaptation-engine-service
  namespace: monitoring
spec:
  selector:
    app: adaptation-engine
  type: ClusterIP
  ports:
  - name: adaptation-engine
    protocol: TCP
    port: 8000
    targetPort: 8000
