package IoT.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Processor extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Processor() {
    super(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x23381bd32c6859a1L, "Processor", "r:589c5fd8-b628-4aae-9e87-31a99b5068a7(IoT.structure)/2537808983820360097");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ARM_0 = new EnumerationDescriptor.MemberDescriptor("ARM", "ARM", 0x23381bd32c6859a2L, "r:589c5fd8-b628-4aae-9e87-31a99b5068a7(IoT.structure)/2537808983820360098");
  private final EnumerationDescriptor.MemberDescriptor myMember_x86_0 = new EnumerationDescriptor.MemberDescriptor("x86", "x86", 0x23381bd32c6859a3L, "r:589c5fd8-b628-4aae-9e87-31a99b5068a7(IoT.structure)/2537808983820360099");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x23381bd32c6859a1L, 0x23381bd32c6859a2L, 0x23381bd32c6859a3L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ARM_0, myMember_x86_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_x86_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ARM":
        return myMember_ARM_0;
      case "x86":
        return myMember_x86_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
