apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alerts
      interval: 1s
      rules:
      - alert: Rule 1
        # Condition for alerting
        expr: test_state{test_state="off"} == 1
        for: 10s
        annotations:
          adaptations: '{"offloading":{"pod_name":"C01","image":"mineIndustry/imageApp1:V0.1","namespace":"default","requirements":{"memory":"500M","cpu":"400m"},"hosts":{"node":{"operator":"In","values":["EdgeWF2"]},"region":{"operator":"In","values":["Level1"]},"cluster":{"operator":"In","values":["ClusterLevel1"]}}}"scaling":{"instances":1,"image":"smartBuilding/imageApp1:V0.1","namespace":"default","requirements":{"memory":"500M","cpu":"400m"},"hosts":{"node":{"operator":"In","values":["Cloud01","Edge01A1","Fog01"]},"region":{"operator":"In","values":["Mine","Floor3"]},"cluster":{"operator":"In","values":["ClusterFloor1","ClusterLevel1"]}}}}'
        labels:
          severity: 'critical'
          actions: '1'
      - alert: Rule 2
        # Condition for alerting
        expr: test_state{test_state="off"} == 1
        for: 10s
        annotations:
          adaptations: '{"operate_actuator":{"broker_ip":"192.168.10.15","port":1883,"topic":"level1/front1/alarm","message":"on"}"operate_actuator":{"broker_ip":"192.168.10.14","port":1883,"topic":"levele1/front2/alarm","message":"on"}}'
        labels:
          severity: 'critical'
          actions: 'all'
      - alert: Test
        # Condition for alerting
        expr: test_state{test_state="off"} == 1
        for: 10s
        annotations:
          adaptations: '{"offloading":{"pod_name":"C01","image":"smartBuilding/imageApp1:V0.1","namespace":"default","requirements":{"memory":"500M","cpu":"400m"},"hosts":{"node":{"operator":"In","values":["Cloud01","Edge01A1"]},"region":{"operator":"In","values":["Floor1"]},"cluster":{"operator":"In","values":["ClusterFloor1"]}}}"scaling":{"instances":2,"image":"smartBuilding/imageApp1:V0.1","namespace":"default","requirements":{"memory":"500M","cpu":"400m"},"hosts":{"node":{"operator":"In","values":["Cloud01"]},"region":{"operator":"In","values":["Floor1"]},"cluster":{"operator":"In","values":["ClusterFloor1"]}}}}'
        labels:
          severity: 'critical'
          actions: 'all'
