package IoT_runtime.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Region_Reference_Constraints extends BaseConstraintsDescriptor {
  public Region_Reference_Constraints() {
    super(CONCEPTS.Region_Reference$ua);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Region_Reference$ua = MetaAdapterFactory.getConcept(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x424863e2f3693460L, "IoT_runtime.structure.Region_Reference");
  }
}
