package IoT.editor;

/*Generated by MPS */

import jetbrains.mps.lang.editor.forms.runtime.AbstractToggleCheckboxAction;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.nodeEditor.selectionRestoring.CellSelector;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.selectionRestoring.WholeCellSelector;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ToggleCheckboxAction_on3pfi_h0 extends AbstractToggleCheckboxAction {
  private final SNode myNode;

  public ToggleCheckboxAction_on3pfi_h0(SNode node) {
    myNode = node;
  }

  protected void doExecute() {
    SPropertyOperations.assign(myNode, PROPS.allActions$UlBc, !(SPropertyOperations.getBoolean(myNode, PROPS.allActions$UlBc)));
  }

  protected CellSelector createCellSelector(EditorCell selectedCell) {
    return new WholeCellSelector();
  }

  private static final class PROPS {
    /*package*/ static final SProperty allActions$UlBc = MetaAdapterFactory.getProperty(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0xcbb176aba26b788L, 0x4dd57832eb42989cL, "allActions");
  }
}
